services:
  db:
    image: postgres:16-alpine
    container_name: lab3_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lab3_flask}
      POSTGRES_USER: ${POSTGRES_USER:-lab3_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cambia_esta_clave}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: lab3_flask
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-lab3_user}:${POSTGRES_PASSWORD:-cambia_esta_clave}@db:5432/${POSTGRES_DB:-lab3_flask}
      SECRET_KEY: ${SECRET_KEY:-cambia_esta_clave_larga}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@laboratorio.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin123*}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
